###
GET http://localhost:8000/events

###
GET http://localhost:8000/events/1

###
GET http://localhost:8000/events/2/spots

###
POST http://localhost:8000/events/1/reserve
Content-Type: application/json

{
  "spots": ["A1"]
}